### ISSUE TITLE
Unable to make demo work

### ISSUE THREAD

**Issue by cFreed-AKA-Alf** [tonystar/drupal-domain-path-rewrite#20]
Interested by this module, I followed steps stated in the "Demo" paragraph of the project page.
But enable Atoms defaults is impossible since the jQuery_update module is missing!

**Comment by anton-staroverov** [comment]
This problem is caused nor by link, nor by `atoms` and has several roots:
1. `entityreference_live_preview` module was changed and now depends on `jquery_update`.
2. So now `atoms` has 11 dependencies in total.
3. `simplytest.me` project limits the number of additional projects to 10, that's why the last one is not downloaded.

I submitted the request to increase this limit: https://www.drupal.org/node/2505927.
**Please put "+1" there to force the request!**

I'm also working on the `atomic` distribution project to simplify demo and installation.

**Comment by anton-staroverov** [comment]
Hooray! The maintainer of `simplytest.me` raised the limit!

Checkout the demo now: http://drupal.tonystar.me/atoms/demo. Should work!

**Comment by cFreed-AKA-Alf** [comment]
Good news! Thanks, I'll test again soon.
